(* let tests = *)
(*   ( "login", *)
(*     [ *)
(*       Alcotest.test_case "login-successful" `Quick (fun () -> *)
(*           H.settings.csrf_checking <- false; *)
(*           let login_fields = [ ("username", "me"); ("password", "pass") ] in *)
(*           let req = make_form_request login_fields in *)
(*           let handler = H.handle_login in *)
(*           let res = *)
(*             req |> Dream.test @@ Dream.memory_sessions @@ Dream.flash @@ handler *)
(*           in *)
(*           is_redirect_to res "/"); *)
(*     ] ) *)
